site_name: DCTwin Engine
repo_name: dctwin

theme:
  name: material
  palette:
    primary: deep purple
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    - toc.follow
    - toc.integrate

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
#  - mkdocstrings:
#      handlers:
#        python:
#          import:
#            - https://docs.python.org/3/objects.inv
#          options:
#            docstring_style: google
#            docstring_options:
#              ignore_init_summary: yes
#            merge_init_into_class: yes
#            show_submodules: no


nav:
  - Home: index.md
  - Get Started:
      - get_started/index.md
      - Installation: get_started/installation.md
      - CFD Tutorial: get_started/cfd_tutorial.md
      - EnergyPlus Tutorial: get_started/eplus_tutorial.md
      - Reducio Tutorial: get_started/reducio_tutorial.md
      - Co-sim Tutorial: get_started/co_sim_tutorial.md
      - Kalibre Tutorial: get_started/kalibre_tutorial.md
  - For Developers:
      - for_developers/index.md
      - Code Stucture: for_developers/code_structure.md
      - Development Guide: for_developers/development_guide.md
      # - Contribution Guide: for_developers/contribution_guide.md
  - Concepts:
      - concepts/index.md
      - Architecture: concepts/architecture.md
  - Reference: reference/

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
- css/code_select.css
